### PR TITLE
Add a trivial Python example

### PR DESCRIPTION
**Pull request by wjam**
Add an example of running a trivial Python program, as a simple introduction to running bacalhau.

Also adds JetBrains IDE directories to gitignore

Fixes #742

### CODE REVIEW

**Comment by enricorotundo** [comment]
Minor things:
* I think there's a typo: We can use the `bacalhau results` command -> `bacalhau get` command
* Is `--wait-timeout-secs 100` strictly needed? I've seen some issues raised by @philwinder recently about failures related to timeouts. If not, let's try to minimize the number of cli options as much as possible and use defaults

**Comment by lukemarsden** [comment]
https://github.com/filecoin-project/bacalhau/issues/742

**Comment by philwinder** [comment]
I've just moved the example to the correct directory and reordered the sidebar. 

Yes, there's no `results` command.

No, that timeout shouldn't be needed, because it should work. But sometimes it doesn't, depending on how big your file is and how busy the network is. I think in this case it should be ok to remove.

I fixed the location. Title changes still need to be done.

**Comment by wjam** [comment]
@philwinder @enricorotundo Can you re-review my changes.

The tests are currently broken - apparently this is due to changes in output for v0.2.6. Is it worth wait until main is fixed, then fixing the tests on this branch, or just merge now?

**Pull request merged**
